language: php
php:
# - 5.4
- 5.5
# - 5.6
services:
- cassandra
before_install:
- sudo apt-get update -q
install:
- composer install
before_script:
- cqlsh 127.0.0.1 -f bootstrap.cql
script:
- bin/evseevnn.php
- bin/duoshuo-stream.php
- bin/duoshuo-stream-persistent.php
- bin/duoshuo-socket.php




